export {
  StudentHome,
  StudentCheckoutQR,
  StudentDiary,
  StudentSubject,
  StudentClubs,
  StudentClub,
  StudentTest,
  StudentAITest,
  StudentEvents,
  StudentAchievements,
  StudentMap,
  StudentShop,
  StudentProfile,
} from './screens/StudentScreens';
